// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4EjIXfNzDXePci9XKT9HjO2uLTW5kokM',
    appId: '1:829407618312:web:154be9da3c62a4612cb8bd',
    messagingSenderId: '829407618312',
    projectId: 'aojr-cloudfirestore',
    authDomain: 'aojr-cloudfirestore.firebaseapp.com',
    storageBucket: 'aojr-cloudfirestore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBx4r-xP8oChpebA37xDh8nFb9l9yOtJ4',
    appId: '1:829407618312:android:59babc91b0cf8e722cb8bd',
    messagingSenderId: '829407618312',
    projectId: 'aojr-cloudfirestore',
    storageBucket: 'aojr-cloudfirestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALdcNGOk0nJqLRv3GYNwpReJqOgslLbqI',
    appId: '1:829407618312:ios:be5b4ad92f23b29a2cb8bd',
    messagingSenderId: '829407618312',
    projectId: 'aojr-cloudfirestore',
    storageBucket: 'aojr-cloudfirestore.appspot.com',
    iosBundleId: 'com.example.persistencesTypes3aojr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALdcNGOk0nJqLRv3GYNwpReJqOgslLbqI',
    appId: '1:829407618312:ios:808b00a8c0ece5b62cb8bd',
    messagingSenderId: '829407618312',
    projectId: 'aojr-cloudfirestore',
    storageBucket: 'aojr-cloudfirestore.appspot.com',
    iosBundleId: 'com.example.persistencesTypes3aojr.RunnerTests',
  );
}
